// AUTO-GENERATED by scripts/sync-projects.ts
// - Pinned GitHub repos for bartlettjude are pulled in automatically.
// - Manual projects are appended from this script.
// - Edit data here directly if you prefer; or run: npm run sync:projects
//
// How to add a project:
// 1) Copy the example object below.
// 2) Paste it into the projects array.
// 3) Update each field with your details. Required fields: slug, name,
//    shortDescription, fullDescription, techStack, status, type.
// 4) Keep the slug unique (it becomes the page URL: /projects/your-slug).
//
// Example:
// const example: Project = {
//   slug: "my-new-idea",
//   name: "My New Idea",
//   shortDescription: "A one-line summary visitors will see in the card.",
//   fullDescription:
//     "A few sentences explaining what the project does, why you built it, and any notable results.",
//   techStack: ["Next.js", "TypeScript", "Tailwind CSS"],
//   status: "In Progress",
//   type: "Web App",
//   role: "Solo Developer",
//   githubUrl: "https://github.com/your-handle/my-new-idea",
//   demoUrl: "https://my-new-idea.example.com",
//   createdAt: "2024-12-01",
//   updatedAt: "2024-12-10",
//   highlighted: true,
// };
export type ProjectStatus = "Planned" | "In Progress" | "Completed";
export type ProjectType = "Web App" | "Tool" | "Experiment" | "Portfolio";

export type Project = {
  slug: string;
  name: string;
  shortDescription: string;
  fullDescription: string;
  techStack: string[];
  status: ProjectStatus;
  type: ProjectType;
  role?: string;
  githubUrl?: string;
  demoUrl?: string;
  createdAt?: string;
  updatedAt?: string;
  highlighted?: boolean;
};

export const projects: Project[] = [
  {
    slug: "verbal-vandal",
    name: "Verbal-Vandal",
    shortDescription: "Tired of polite conversation? Verbal Vandal is your mischievous AI sidekick that crafts clever, hilarious, and over-the-top insults on demand. It’s snark served fresh — perfect for roasting friends, enemies, or your own questionable life choices. All in good fun, no real damage (we promise).",
    fullDescription: "Tired of polite conversation? Verbal Vandal is your mischievous AI sidekick that crafts clever, hilarious, and over-the-top insults on demand. It’s snark served fresh — perfect for roasting friends, enemies, or your own questionable life choices. All in good fun, no real damage (we promise).",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS"],
    status: "Completed",
    type: "Web App",
    role: "Solo Developer",
    githubUrl: "https://github.com/bartlettjude/Verbal-Vandal",
    demoUrl: "https://verbal-vandal.vercel.app",
    createdAt: "2025-10-30T22:13:54Z",
    updatedAt: "2026-01-24T18:01:38Z",
    highlighted: true
  },
  {
    slug: "music-train",
    name: "Music-Train",
    shortDescription: "Music Train is a retro-styled audio workstation for musicians and producers. Load any audio file or record directly, and instantly detect the key, BPM, and chord progression. Shift pitch up to ±12 semitones, time-stretch without affecting pitch, and apply effects like EQ, reverb, and lo-fi processing. Features real-time spectrum analysis, LUFS loud",
    fullDescription: "Music Train is a retro-styled audio workstation for musicians and producers. Load any audio file or record directly, and instantly detect the key, BPM, and chord progression. Shift pitch up to ±12 semitones, time-stretch without affecting pitch, and apply effects like EQ, reverb, and lo-fi processing. Features real-time spectrum analysis, LUFS loud",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS"],
    status: "Completed",
    type: "Web App",
    role: "Solo Developer",
    githubUrl: "https://github.com/bartlettjude/Music-Train",
    demoUrl: "https://github.com/bartlettjude/Music-Train",
    createdAt: "2026-01-23T03:36:20Z",
    updatedAt: "2026-01-23T23:16:15Z",
    highlighted: true
  }
];

function sortValue(dateString?: string) {
  return dateString ? new Date(dateString).getTime() : 0;
}

export function getAllProjects(): Project[] {
  return [...projects].sort((a, b) => sortValue(b.createdAt) - sortValue(a.createdAt));
}

export function getProjectBySlug(slug: string): Project | null {
  return projects.find((project) => project.slug === slug) ?? null;
}

export function getHighlightedProjects(): Project[] {
  return projects.filter((project) => project.highlighted);
}
